---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create Azure Deploy
  azure_rm_deployment:
    state: present
    resource_group_name: dev-ops-cle
    template_link: 'https://raw.githubusercontent.com/AnuPriya2131/testing_repo/master/BigData/maindeploy.json'
