---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
      dataFactoryName: "{{ ansible_env.dataFactoryName }}"
      Storagekey: "{{ ansible_env.Storagekey }}"
      spkey: "{{ ansible_env.spkey }}"
      servicePrincipalId: "{{ ansible_env.servicePrincipalId }}"
      hostSubscriptionId: "{{ ansible_env.hostSubscriptionId }}"
      tenant: "{{ ansible_env.tenant }}"
      ClusterUserName: "{{ ansible_env.ClusterUserName }}"
      ClusterPassword: "{{ ansible_env.ClusterPassword }}"
      sqlseverkey: "{{ ansible_env.sqlseverkey }}"
      environment: "{{ ansible_env.environment }}"
      resourcesgpname: "{{ ansible_env.resourcesgpname }}"
      location: eastus2
      templateLink: 'https://raw.githubusercontent.com/sangaml/testing_repo/master/BigData/maindeploy.json'
  tasks:
    - name: Deploy ARM template
      azure_rm_deployment:
        subscription_id: 4ff8750b-e2fa-4db8-84c8-86abd50d3868
        client_id: 226d0c4c-4b98-41e4-8ff0-0ef11d1e54f4
        tenant_id: c160a942-c869-429f-8a96-f8c8296d57db
        secret_id: qaEbeMNs2mNxacfqDrez24/TwVgQVyPKL8rjTtd0VA4=
        resource_group_name: sangam
        location: "eastus2"
        state: present
        parameters: 
          dataFactoryName: 
            value: "{{ dataFactoryName }}"
          Storagekey: 
            value: "{{ Storagekey }}"
          spkey: 
            value: "{{ spkey }}"
          servicePrincipalId: 
            value: "{{ servicePrincipalId }}"
          hostSubscriptionId: 
            value: "{{ hostSubscriptionId }}"
          tenant: 
            value: "{{ tenant }}"
          ClusterUserName: 
            value: "{{ ClusterUserName }}"
          ClusterPassword: 
            value: "{{ ClusterPassword }}"
          sqlseverkey: 
            value: "{{ sqlseverkey }}"
          environment: 
            value: "{{ environment }}"
          resourcesgpname: 
            value: "{{ resourcesgpname }}"                 
        template_link: "https://raw.githubusercontent.com/sangaml/testing_repo/master/BigData/maindeploy.json"
